version: '3'

networks:
  strategio-network:

services:
  app:
    build: .
    restart: "no"
    networks:
      - strategio-network
    ports:
      - "80:80"
    volumes:
      - $PWD:/var/www/html:cached