version: '3'

networks:
  nginx_proxy_network:
    external:
      name: nginx_proxy_network

services:
  app:
    build: .
    restart: "always"
    networks:
      - nginx_proxy_network
    environment:
      VIRTUAL_HOST: maockovanismysl.cz
      VIRTUAL_HOST_ALIAS: www.maockovanismysl.cz
      LETSENCRYPT_HOST: maockovanismysl.cz,www.maockovanismysl.cz
    volumes:
      - $PWD:/var/www/html:cached